server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/dasi
    #username: root
    #password: 1234
    url: jdbc:mysql://mysql.coffit.today:3306/dasi
    username: HIkdt6
    password: HIkdt6



  mvc:
    view:
      suffix: .html

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 300MB
      location: D:/dasi-project/

  mail:
    host: smtp.gmail.com
    port: 465
    username: projectdasi2023@gmail.com
    password: vnwl zyjg akyi uhpb
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true
  graphql:
    cors:
      allowed-origins:
        - http://localhost:8000

mybatis:
  mapper-locations: mappers/**/*.xml

  TypeHandler: com.project.dasi.dto.UserType


pagehelper:
  helper-dialect: mysql
  auto-dialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true

image:
  image-dir: img